version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tus"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4ezqv1es2hro"
s3_prefix = "tus"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

