AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tus
  
  Twitter User Scavenger

Globals:
  Function:
    Timeout: 5

Resources:
  TusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: tus
      Runtime: go1.x
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: tus-available
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Input: '{"usernames": ["krudler", "crudler", "hypertrace", "derek", "derekmiller"]}'
            Schedule: rate(15 minutes)
  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref TusFunction
      Qualifier: "$LATEST"
      MaximumRetryAttempts: 0
      DestinationConfig:
        OnSuccess:
          Destination: arn:aws:sns:us-west-2:262965443437:tus-available